### ISSUE TITLE
'dict object' has no attribute 'stdout' in set_fact

### ISSUE THREAD

**Issue by dspruell-s01** [trombik/ansible-role-unbound#26]
##### ISSUE TYPE
 - Bug Report

##### ROLE VERSION
```
4.0.0
```

##### CONFIGURATION
ansible.cfg:
```
[defaults]
ansible_managed = "!!! Ansible managed - changes will be overridden"
interpreter_python = auto_silent

[privilege_escalation]
become = True
```

##### OS / ENVIRONMENT
- Debian GNU/Linux 9.12 (stretch)
- Linux 4.9.0-12-amd64
- ansible 2.7.6
    - config file = None
    - configured module search path = ['/home/dspruell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    - ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
    - executable location = /usr/local/bin/ansible
    - python version = 3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]

##### SUMMARY
Role application fails with error against Debian:

```
TASK [trombik.unbound : set_fact] ***************************************************************************************************************************
fatal: [hecamede]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '[redacted]/roles/trombik.unbound/tasks/main.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

```

##### STEPS TO REPRODUCE
1. Install role
```
$ ansible-galaxy role install -p roles trombik.unbound
- downloading role 'unbound', owned by trombik
- downloading role from https://github.com/trombik/ansible-role-unbound/archive/4.0.0.tar.gz
- extracting trombik.unbound to /Users/dspruell/devel/analysis-lab-ansible/roles/trombik.unbound
- trombik.unbound (4.0.0) was installed successfully
```
2. Configure playbook
```
---
# dns.yml
- hosts: dns
  roles:
    - trombik.nsd
    - trombik.unbound
```
3. Apply playbook
```
$ ansible-playbook -i hosts --ask-vault-pass dns.yml
```

##### EXPECTED RESULTS
Successful role application.

##### ACTUAL RESULTS
Failure as indicated.

##### NOTES
The following modification seems to have resolved and allowed Ansible to continue to apply role.

```patch
--- roles/trombik.unbound/tasks/fact-Debian.yml.bak	2020-09-01 20:06:49.000000000 -0700
+++ roles/trombik.unbound/tasks/fact-Debian.yml	2020-09-01 20:07:07.000000000 -0700
@@ -6,4 +6,4 @@
   check_mode: no
   changed_when: false
   when:
-    - ansible_distribution == 'Ubuntu'
+    - ansible_distribution == 'Debian'
```

**Comment by dspruell-s01** [comment]
Issue appears to have occurred in this set of tasks in `tasks/main.yml`:

```
- name: Include fact-{{ ansible_os_family }}.yml
  include_tasks: "fact-{{ ansible_os_family }}.yml"

- name: Assert register_unbound_version is defined
  assert:
    that:
      - register_unbound_version is defined
    msg: |
      [BUG] register_unbound_version must be defined by
      fact-{{ ansible_os_family }}.yml, but register_unbound_version is not
      defined. This means the role has a bug in it.

- set_fact:
    unbound_version: "{{ register_unbound_version.stdout }}"
```

```register_unbound_version``` was not being defined and it seems like the assert may not have quite caught it since the set_fact finds no output attached to the variable.
